In [1]:
import sys
import os
sys.path.append(os.path.abspath(".."))

# 📌 Import Libraries

In [2]:
import numpy as np
import pandas as pd
from src.preprocessing import load_data, clean_data
from src.feature_engineering import create_features, aggregate_daily

# 📌 Load Raw Data

In [3]:
df = load_data('../data/raw/restaurant_orders.csv')
df.head()

,Order ID,Customer Name,Food Item,Category,Quantity,Price,Payment Method,Order Time
0,2268,Mary Vega DDS,Pasta,Main,5,16.52,Cash,2025-02-02 14:28:41
1,3082,Brandon Myers,Brownie,Dessert,4,17.27,Debit Card,2025-06-08 10:57:47
2,3160,Margaret Wells,Pasta,Main,1,3.37,Credit Card,2025-03-04 07:41:41
3,1272,Michael Matthews,Pasta,Main,5,2.20,Online Payment,2025-05-15 12:43:45
4,9447,Connor Williams,Soup,Starter,1,12.23,Cash,2025-03-15 14:25:56

# 📌 Clean the Data

In [4]:
df = clean_data(df)
df.head()

,Order ID,Customer Name,Food Item,Category,Quantity,Price,Payment Method,Order Time
0,2268,Mary Vega DDS,Pasta,Main,5,16.52,Cash,2025-02-02 14:28:41
1,3082,Brandon Myers,Brownie,Dessert,4,17.27,Debit Card,2025-06-08 10:57:47
2,3160,Margaret Wells,Pasta,Main,1,3.37,Credit Card,2025-03-04 07:41:41
3,1272,Michael Matthews,Pasta,Main,5,2.20,Online Payment,2025-05-15 12:43:45
4,9447,Connor Williams,Soup,Starter,1,12.23,Cash,2025-03-15 14:25:56

# 📌 Create Features

In [5]:
df = create_features(df)
df.head()

,Order ID,Customer Name,Food Item,Category,Quantity,Price,Payment Method,Order Time,Total_Revenue,Hour,Day,Month,Weekday,Weekend
0,2268,Mary Vega DDS,Pasta,Main,5,16.52,Cash,2025-02-02 14:28:41,82.60,14,2,2,6,1
1,3082,Brandon Myers,Brownie,Dessert,4,17.27,Debit Card,2025-06-08 10:57:47,69.08,10,8,6,6,1
2,3160,Margaret Wells,Pasta,Main,1,3.37,Credit Card,2025-03-04 07:41:41,3.37,7,4,3,1,0
3,1272,Michael Matthews,Pasta,Main,5,2.20,Online Payment,2025-05-15 12:43:45,11.00,12,15,5,3,0
4,9447,Connor Williams,Soup,Starter,1,12.23,Cash,2025-03-15 14:25:56,12.23,14,15,3,5,1

# 📌 Aggregate Daily Order Data

In [6]:
daily_data = aggregate_daily(df)
daily_data.head()

,Date,Quantity,Total_Revenue,Day,Month,Weekday,Weekend,Lag_1,Lag_2,Lag_3,Rolling_Mean_3,Rolling_Mean_7
6,2025-01-08,6,33.29,8,1,2,0,26.14,221.98,24.29,93.803333,80.360000
7,2025-01-09,5,60.10,9,1,3,0,33.29,26.14,221.98,39.843333,85.998571
8,2025-01-10,5,20.78,10,1,4,0,60.10,33.29,26.14,38.056667,60.982857
9,2025-01-11,7,53.35,11,1,5,1,20.78,60.10,33.29,44.743333,62.847143
10,2025-01-12,12,162.91,12,1,6,1,53.35,20.78,60.10,79.013333,82.650000

# 📌 Save Processed Data

In [7]:
daily_data.to_csv('../data/processed/daily_sales.csv', index=False)
print("Processed daily sales saved successfully!")

Processed daily sales saved successfully!