# 📌 Import Libraries

In [1]:
import sys
import os
sys.path.append(os.path.abspath(".."))

In [2]:
import pandas as pd
from src.modeling import train_model, save_model

# 📌 Load Processed Dataset

In [3]:
df = pd.read_csv('../data/processed/daily_sales.csv')
df.head()

,Date,Quantity,Total_Revenue,Day,Month,Weekday,Weekend,Lag_1,Lag_2,Lag_3,Rolling_Mean_3,Rolling_Mean_7
0,2025-01-08,6,33.29,8,1,2,0,26.14,221.98,24.29,93.803333,80.360000
1,2025-01-09,5,60.10,9,1,3,0,33.29,26.14,221.98,39.843333,85.998571
2,2025-01-10,5,20.78,10,1,4,0,60.10,33.29,26.14,38.056667,60.982857
3,2025-01-11,7,53.35,11,1,5,1,20.78,60.10,33.29,44.743333,62.847143
4,2025-01-12,12,162.91,12,1,6,1,53.35,20.78,60.10,79.013333,82.650000

# 📌 Sort Data by Date (Important for Time Series)

In [4]:
df = df.sort_values('Date')
df.reset_index(drop=True, inplace=True)

df.head()

,Date,Quantity,Total_Revenue,Day,Month,Weekday,Weekend,Lag_1,Lag_2,Lag_3,Rolling_Mean_3,Rolling_Mean_7
0,2025-01-08,6,33.29,8,1,2,0,26.14,221.98,24.29,93.803333,80.360000
1,2025-01-09,5,60.10,9,1,3,0,33.29,26.14,221.98,39.843333,85.998571
2,2025-01-10,5,20.78,10,1,4,0,60.10,33.29,26.14,38.056667,60.982857
3,2025-01-11,7,53.35,11,1,5,1,20.78,60.10,33.29,44.743333,62.847143
4,2025-01-12,12,162.91,12,1,6,1,53.35,20.78,60.10,79.013333,82.650000

# 📌 Define Features and  Target Variable

In [5]:
features = [
    'Quantity',
    'Day',
    'Month',
    'Weekday',
    'Weekend',
    'Lag_1',
    'Lag_2',
    'Lag_3',
    'Rolling_Mean_3',
    'Rolling_Mean_7'
]

X = df[features]
y = df['Total_Revenue']

print("Feature shape:", X.shape)
print("Target shape:", y.shape)

Feature shape: (194, 10)
Target shape: (194,)

# 📌Time-Based Set

In [6]:
split = int(len(df) * 0.8)

X_train = X[:split]
y_train = y[:split]
X_test = X[split:]
y_test = y[split:]

print("Test size:", X_test.shape)
print("Train size:", X_train.shape)

Test size: (39, 10)
Train size: (155, 10)

# 📌 Train Model

In [7]:
model = train_model(X_train, y_train)

print("Model trained successfully")

Model trained successfully

# 📌 Save Trained Model

In [8]:
save_model(model, '../models/final_model.pkl')

print("Model saved successfully in models/final_model.pkl")

Model saved successfully in models/final_model.pkl